spring.application.name=api-publica
# Dados de conexão (Pegue no painel do Supabase > Settings > Database > JDBC)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.gatnrpvbytllptsnnnvd
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-stacktrace=never
spring.web.error.include-message=always
spring.web.error.include-exception=false

# Forçar a aplicação a exibir erros detalhados de inicialização
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Para o Swagger (Documentação)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.flyway.baseline-on-migrate=true