spring.application.name=api-publica
# Dados de conexão (Pegue no painel do Supabase > Settings > Database > JDBC)
spring.datasource.url=jdbc:postgresql://db.gatnrpvbytllptsnnnvd.supabase.co:5432/postgres?user=postgres&password=${DB_PASSWORD}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Para o Swagger (Documentação)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html